### ISSUE TITLE
Main document

### ISSUE THREAD

**Issue by schtl** [TomasBrezina/NeuralNetworkRacing#4]
Great work! Is there a detailed description of the source code? We want to use your program as an example for deep learning in the school, so it would be nice to stay in contact with you ...

**Comment by TomasBrezina** [comment]
Thank you! The only documentation is in the README file and in this older [video](https://www.youtube.com/watch?v=B0ptl-NChJQ&lc=Ugze_vT3rUOV2Kzb-Md4AaABAg). You are free to use to it for whatever purpose as long as it is not commercial. Also you have to keep in mind that I was a high school student when I wrote this project - I'm not so proud of this code anymore 😄
